---
# Template: 1.1.0
name: "Lint / Bash / TestManSH"

on:
  push:
    branches:
      - "feature/*"
      - "develop"
      - "main"

jobs:
  lint-bash-testmansh:
    runs-on: "ubuntu-latest"
    steps:

      - name: "Check out repository code"
        uses: "actions/checkout@main"

      - name: "Prepare build environment"
        run: "./bin/devtmsh-lib"

      - name: "Build app"
        run: "./bin/devtmsh-build"

      - name: "Run linter"
        run: "./lib/testmansh -t -c build/testmansh"
...
